### ISSUE TITLE
Compile errors appeared in @rstore/vue, latest version - 0.5.9

### ISSUE THREAD

**Issue by s-sreeram-paperculture** [directus/rstore#28]
### Describe the bug

Getting these compilation errors in rstore/vue when run `npm run serve` in the latest version but the same code worked in the version 0.5.6

![Image](https://github.com/user-attachments/assets/b1872eb0-211c-44c5-a5b5-6dce1ac1fa84)

### Reproduction

- Follow the steps in rstore guide for ts-vue application in the latest version, it throws compilation errors for `createStore` and `defineItemType<T>.model`

### System Info

```shell
System:
    OS: macOS 14.7.4
    CPU: (12) arm64 Apple M3 Pro
    Memory: 10.88 GB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.14.0 - /usr/local/bin/node
    npm: 10.9.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 134.0.6998.166
  npmPackages:
    @rstore/vue: ^0.5.9 => 0.5.9 
    vue: ^3.2.13 => 3.5.13
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/Akryum/rstore/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/Akryum/rstore/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://rstore.starpad.dev/guide/).
- [x] Check that there isn't [already an issue](https://github.com/Akryum/rstore/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Akryum/rstore/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Akryum** [comment]
You need to update your TypeScript version to at least v5.0
